[package]
rust-version.workspace = true
name = "sdkwork-api-aiot-standalone-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-api-aiot-assembly.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-iam-web-adapter.workspace = true
sdkwork-web-bootstrap.workspace = true
tokio.workspace = true
